<?php

defined('BASEPATH') or exit('No direct script access allowed!');

class Migration_Install_table_language extends CI_Migration
{
	public function __construct()
	{
		$this->load->dbforge();
		$this->load->database();
	}

	public function up()
	{

		$this->dbforge->drop_table('language', TRUE);

		$this->dbforge->add_field([
			'lang_id' => [
				'type' => 'VARCHAR',
				'constraint' => '2',
			],
			'lang_name' => [
				'type' => 'VARCHAR',
				'constraint' => '255'
			],
			'is_used' => [
				'type' => 'INT',
				'constraint' => '1',
				'default' => '1'
			]
		]);

		$this->dbforge->add_key('lang_id',TRUE);
		$this->dbforge->create_table('language');

		// insert list language

		$list_languages = [
			['lang_id' => 'ab', 'lang_name' => 'Abkhazian'],
			['lang_id' => 'aa', 'lang_name' => 'Afar'],
			['lang_id' => 'af', 'lang_name' => 'Afrikaans'],
			['lang_id' => 'ak', 'lang_name' => 'Akan'],
			['lang_id' => 'sq', 'lang_name' => 'Albanian'],
			['lang_id' => 'am', 'lang_name' => 'Amharic'],
			['lang_id' => 'ar', 'lang_name' => 'Arabic'],
			['lang_id' => 'an', 'lang_name' => 'Aragonese'],
			['lang_id' => 'hy', 'lang_name' => 'Armenian'],
			['lang_id' => 'as', 'lang_name' => 'Assamese'],
			['lang_id' => 'av', 'lang_name' => 'Avaric'],
			['lang_id' => 'ae', 'lang_name' => 'Avestan'],
			['lang_id' => 'ay', 'lang_name' => 'Aymara'],
			['lang_id' => 'az', 'lang_name' => 'Azerbaijani'],
			['lang_id' => 'bm', 'lang_name' => 'Bambara'],
			['lang_id' => 'ba', 'lang_name' => 'Bashkir'],
			['lang_id' => 'eu', 'lang_name' => 'Basque'],
			['lang_id' => 'be', 'lang_name' => 'Belarusian'],
			['lang_id' => 'bn', 'lang_name' => 'Bengali'],
			['lang_id' => 'bh', 'lang_name' => 'Bihari languages'],
			['lang_id' => 'bi', 'lang_name' => 'Bislama'],
			['lang_id' => 'bs', 'lang_name' => 'Bosnian'],
			['lang_id' => 'br', 'lang_name' => 'Breton'],
			['lang_id' => 'bg', 'lang_name' => 'Bulgarian'],
			['lang_id' => 'my', 'lang_name' => 'Burmese'],
			['lang_id' => 'ca', 'lang_name' => 'Catalan, Vallang_idian'],
			['lang_id' => 'km', 'lang_name' => 'Central Khmer'],
			['lang_id' => 'ch', 'lang_name' => 'Chamorro'],
			['lang_id' => 'ce', 'lang_name' => 'Chechen'],
			['lang_id' => 'ny', 'lang_name' => 'Chichewa, Chewa, Nyanja'],
			['lang_id' => 'zh', 'lang_name' => 'Chinese'],
			['lang_id' => 'cu', 'lang_name' => 'Church Slavonic, Old Bulgarian, Old Church Slavonic'],
			['lang_id' => 'cv', 'lang_name' => 'Chuvash'],
			['lang_id' => 'kw', 'lang_name' => 'Cornish'],
			['lang_id' => 'co', 'lang_name' => 'Corsican'],
			['lang_id' => 'cr', 'lang_name' => 'Cree'],
			['lang_id' => 'hr', 'lang_name' => 'Croatian'],
			['lang_id' => 'cs', 'lang_name' => 'Czech'],
			['lang_id' => 'da', 'lang_name' => 'Danish'],
			['lang_id' => 'dv', 'lang_name' => 'Divehi, Dhivehi, Maldivian'],
			['lang_id' => 'nl', 'lang_name' => 'Dutch, Flemish'],
			['lang_id' => 'dz', 'lang_name' => 'Dzongkha'],
			['lang_id' => 'en', 'lang_name' => 'English'],
			['lang_id' => 'eo', 'lang_name' => 'Esperanto'],
			['lang_id' => 'et', 'lang_name' => 'Estonian'],
			['lang_id' => 'ee', 'lang_name' => 'Ewe'],
			['lang_id' => 'fo', 'lang_name' => 'Faroese'],
			['lang_id' => 'fj', 'lang_name' => 'Fijian'],
			['lang_id' => 'fi', 'lang_name' => 'Finnish'],
			['lang_id' => 'fr', 'lang_name' => 'Frlang_idh'],
			['lang_id' => 'ff', 'lang_name' => 'Fulah'],
			['lang_id' => 'gd', 'lang_name' => 'Gaelic, Scottish Gaelic'],
			['lang_id' => 'gl', 'lang_name' => 'Galician'],
			['lang_id' => 'lg', 'lang_name' => 'Ganda'],
			['lang_id' => 'ka', 'lang_name' => 'Georgian'],
			['lang_id' => 'de', 'lang_name' => 'German'],
			['lang_id' => 'ki', 'lang_name' => 'Gikuyu, Kikuyu'],
			['lang_id' => 'el', 'lang_name' => 'Greek (Modern)'],
			['lang_id' => 'kl', 'lang_name' => 'Greenlandic, Kalaallisut'],
			['lang_id' => 'gn', 'lang_name' => 'Guarani'],
			['lang_id' => 'gu', 'lang_name' => 'Gujarati'],
			['lang_id' => 'ht', 'lang_name' => 'Haitian, Haitian Creole'],
			['lang_id' => 'ha', 'lang_name' => 'Hausa'],
			['lang_id' => 'he', 'lang_name' => 'Hebrew'],
			['lang_id' => 'hz', 'lang_name' => 'Herero'],
			['lang_id' => 'hi', 'lang_name' => 'Hindi'],
			['lang_id' => 'ho', 'lang_name' => 'Hiri Motu'],
			['lang_id' => 'hu', 'lang_name' => 'Hungarian'],
			['lang_id' => 'is', 'lang_name' => 'Icelandic'],
			['lang_id' => 'io', 'lang_name' => 'Ido'],
			['lang_id' => 'ig', 'lang_name' => 'Igbo'],
			['lang_id' => 'id', 'lang_name' => 'Indonesian'],
			['lang_id' => 'ia', 'lang_name' => 'Interlingua (International Auxiliary Language Association)'],
			['lang_id' => 'ie', 'lang_name' => 'Interlingue'],
			['lang_id' => 'iu', 'lang_name' => 'Inuktitut'],
			['lang_id' => 'ik', 'lang_name' => 'Inupiaq'],
			['lang_id' => 'ga', 'lang_name' => 'Irish'],
			['lang_id' => 'it', 'lang_name' => 'Italian'],
			['lang_id' => 'ja', 'lang_name' => 'Japanese'],
			['lang_id' => 'jv', 'lang_name' => 'Javanese'],
			['lang_id' => 'kn', 'lang_name' => 'Kannada'],
			['lang_id' => 'kr', 'lang_name' => 'Kanuri'],
			['lang_id' => 'ks', 'lang_name' => 'Kashmiri'],
			['lang_id' => 'kk', 'lang_name' => 'Kazakh'],
			['lang_id' => 'rw', 'lang_name' => 'Kinyarwanda'],
			['lang_id' => 'kv', 'lang_name' => 'Komi'],
			['lang_id' => 'kg', 'lang_name' => 'Kongo'],
			['lang_id' => 'ko', 'lang_name' => 'Korean'],
			['lang_id' => 'kj', 'lang_name' => 'Kwanyama, Kuanyama'],
			['lang_id' => 'ku', 'lang_name' => 'Kurdish'],
			['lang_id' => 'ky', 'lang_name' => 'Kyrgyz'],
			['lang_id' => 'lo', 'lang_name' => 'Lao'],
			['lang_id' => 'la', 'lang_name' => 'Latin'],
			['lang_id' => 'lv', 'lang_name' => 'Latvian'],
			['lang_id' => 'lb', 'lang_name' => 'Letzeburgesch, Luxembourgish'],
			['lang_id' => 'li', 'lang_name' => 'Limburgish, Limburgan, Limburger'],
			['lang_id' => 'ln', 'lang_name' => 'Lingala'],
			['lang_id' => 'lt', 'lang_name' => 'Lithuanian'],
			['lang_id' => 'lu', 'lang_name' => 'Luba-Katanga'],
			['lang_id' => 'mk', 'lang_name' => 'Macedonian'],
			['lang_id' => 'mg', 'lang_name' => 'Malagasy'],
			['lang_id' => 'ms', 'lang_name' => 'Malay'],
			['lang_id' => 'ml', 'lang_name' => 'Malayalam'],
			['lang_id' => 'mt', 'lang_name' => 'Maltese'],
			['lang_id' => 'gv', 'lang_name' => 'Manx'],
			['lang_id' => 'mi', 'lang_name' => 'Maori'],
			['lang_id' => 'mr', 'lang_name' => 'Marathi'],
			['lang_id' => 'mh', 'lang_name' => 'Marshallese'],
			['lang_id' => 'ro', 'lang_name' => 'Moldovan, Moldavian, Romanian'],
			['lang_id' => 'mn', 'lang_name' => 'Mongolian'],
			['lang_id' => 'na', 'lang_name' => 'Nauru'],
			['lang_id' => 'nv', 'lang_name' => 'Navajo, Navaho'],
			['lang_id' => 'nd', 'lang_name' => 'Northern Ndebele'],
			['lang_id' => 'ng', 'lang_name' => 'Ndonga'],
			['lang_id' => 'ne', 'lang_name' => 'Nepali'],
			['lang_id' => 'se', 'lang_name' => 'Northern Sami'],
			['lang_id' => 'no', 'lang_name' => 'Norwegian'],
			['lang_id' => 'nb', 'lang_name' => 'Norwegian Bokmål'],
			['lang_id' => 'nn', 'lang_name' => 'Norwegian Nynorsk'],
			['lang_id' => 'ii', 'lang_name' => 'Nuosu, Sichuan Yi'],
			['lang_id' => 'oc', 'lang_name' => 'Occitan (post 1500)'],
			['lang_id' => 'oj', 'lang_name' => 'Ojibwa'],
			['lang_id' => 'or', 'lang_name' => 'Oriya'],
			['lang_id' => 'om', 'lang_name' => 'Oromo'],
			['lang_id' => 'os', 'lang_name' => 'Ossetian, Ossetic'],
			['lang_id' => 'pi', 'lang_name' => 'Pali'],
			['lang_id' => 'pa', 'lang_name' => 'Panjabi, Punjabi'],
			['lang_id' => 'ps', 'lang_name' => 'Pashto, Pushto'],
			['lang_id' => 'fa', 'lang_name' => 'Persian'],
			['lang_id' => 'pl', 'lang_name' => 'Polish'],
			['lang_id' => 'pt', 'lang_name' => 'Portuguese'],
			['lang_id' => 'qu', 'lang_name' => 'Quechua'],
			['lang_id' => 'rm', 'lang_name' => 'Romansh'],
			['lang_id' => 'rn', 'lang_name' => 'Rundi'],
			['lang_id' => 'ru', 'lang_name' => 'Russian'],
			['lang_id' => 'sm', 'lang_name' => 'Samoan'],
			['lang_id' => 'sg', 'lang_name' => 'Sango'],
			['lang_id' => 'sa', 'lang_name' => 'Sanskrit'],
			['lang_id' => 'sc', 'lang_name' => 'Sardinian'],
			['lang_id' => 'sr', 'lang_name' => 'Serbian'],
			['lang_id' => 'sn', 'lang_name' => 'Shona'],
			['lang_id' => 'sd', 'lang_name' => 'Sindhi'],
			['lang_id' => 'si', 'lang_name' => 'Sinhala, Sinhalese'],
			['lang_id' => 'sk', 'lang_name' => 'Slovak'],
			['lang_id' => 'sl', 'lang_name' => 'Slovenian'],
			['lang_id' => 'so', 'lang_name' => 'Somali'],
			['lang_id' => 'st', 'lang_name' => 'Sotho, Southern'],
			['lang_id' => 'nr', 'lang_name' => 'South Ndebele'],
			['lang_id' => 'es', 'lang_name' => 'Spanish, Castilian'],
			['lang_id' => 'su', 'lang_name' => 'Sundanese'],
			['lang_id' => 'sw', 'lang_name' => 'Swahili'],
			['lang_id' => 'ss', 'lang_name' => 'Swati'],
			['lang_id' => 'sv', 'lang_name' => 'Swedish'],
			['lang_id' => 'tl', 'lang_name' => 'Tagalog'],
			['lang_id' => 'ty', 'lang_name' => 'Tahitian'],
			['lang_id' => 'tg', 'lang_name' => 'Tajik'],
			['lang_id' => 'ta', 'lang_name' => 'Tamil'],
			['lang_id' => 'tt', 'lang_name' => 'Tatar'],
			['lang_id' => 'te', 'lang_name' => 'Telugu'],
			['lang_id' => 'th', 'lang_name' => 'Thai'],
			['lang_id' => 'bo', 'lang_name' => 'Tibetan'],
			['lang_id' => 'ti', 'lang_name' => 'Tigrinya'],
			['lang_id' => 'to', 'lang_name' => 'Tonga (Tonga Islands)'],
			['lang_id' => 'ts', 'lang_name' => 'Tsonga'],
			['lang_id' => 'tn', 'lang_name' => 'Tswana'],
			['lang_id' => 'tr', 'lang_name' => 'Turkish'],
			['lang_id' => 'tk', 'lang_name' => 'Turkmen'],
			['lang_id' => 'tw', 'lang_name' => 'Twi'],
			['lang_id' => 'ug', 'lang_name' => 'Uighur, Uyghur'],
			['lang_id' => 'uk', 'lang_name' => 'Ukrainian'],
			['lang_id' => 'ur', 'lang_name' => 'Urdu'],
			['lang_id' => 'uz', 'lang_name' => 'Uzbek'],
			['lang_id' => 've', 'lang_name' => 'Venda'],
			['lang_id' => 'vi', 'lang_name' => 'Vietnamese'],
			['lang_id' => 'vo', 'lang_name' => 'Volap_k'],
			['lang_id' => 'wa', 'lang_name' => 'Walloon'],
			['lang_id' => 'cy', 'lang_name' => 'Welsh'],
			['lang_id' => 'fy', 'lang_name' => 'Western Frisian'],
			['lang_id' => 'wo', 'lang_name' => 'Wolof'],
			['lang_id' => 'xh', 'lang_name' => 'Xhosa'],
			['lang_id' => 'yi', 'lang_name' => 'Yiddish'],
			['lang_id' => 'yo', 'lang_name' => 'Yoruba'],
			['lang_id' => 'za', 'lang_name' => 'Zhuang, Chuang'],
			['lang_id' => 'zu', 'lang_name' => 'Zulu']
		];

		$this->db->insert_batch('language',$list_languages,300);

	}

	public function down(){
		$this->dbforge->drop_table('language',TRUE);
	}

}
